-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 17:49:54 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enovos` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enovos` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enovos`.`t_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `is_admin` TINYINT(1) NULL DEFAULT 0,
  `is_activated` TINYINT(1) NULL DEFAULT 0,
  `security_hash` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enovos`.`t_devices` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_devices` (
  `id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `t_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_devices_t_users_idx` (`t_users_id` ASC),
  CONSTRAINT `fk_t_devices_t_users`
    FOREIGN KEY (`t_users_id`)
    REFERENCES `mydb`.`t_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enovos`.`t_data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `light` FLOAT NULL,
  `temperature` FLOAT NULL,
  `pressure` INT NULL,
  `t_devices_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_data_t_devices1_idx` (`t_devices_id` ASC),
  CONSTRAINT `fk_t_data_t_devices1`
    FOREIGN KEY (`t_devices_id`)
    REFERENCES `mydb`.`t_devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
